version: '3'

services:
  chaddi-tg:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: on-failure
    environment:
      - BOT_USERNAME=${BOT_USERNAME}
      - TG_TOKEN=${TG_TOKEN}
      - GM_CHANNELS=${GM_CHANNELS}
      - HI_RESPONSE=${HI_RESPONSE}
      - ENABLE_WEBHOOK=${ENABLE_WEBHOOK}
      - WEBHOOK_URL=${WEBHOOK_URL}
