global:
  scrape_interval: 1s
  evaluation_interval: 30s

scrape_configs:
  - job_name: chaddi-tg
    honor_labels: true
    metrics_path: "/chaddi"
    scheme: "https"
    static_configs:
      - targets: ["chaddi-host"]
