version: "3.7"

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    command: --config.file=/etc/prometheus/prometheus.yaml
    expose:
      - 9090
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
      - ./docker-data/prometheus-data:/prometheus

  grafana:
    image: grafana/grafana:7.0.3-ubuntu
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      # - ./grafana.ini:/etc/grafana/grafana.ini
      - ./docker-data/grafana-data:/var/lib/grafana
    environment:
      - GF_AUTH_BASIC_ENABLED=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
