{
 "title": "chaddi-tg",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Group Activity over time ",
   "type": "graph",
   "gridPos": { "h": 11, "w": 15, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "chaddi_messages_count_total{job=\"chaddi-tg\"}",
     "legendFormat": "{{group_id}}"
    }
   ]
  },
  {
   "title": "Total user and system CPU time spent in seconds",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_cpu_seconds_total{job=\"chaddi-tg\"}"
    }
   ]
  },
  {
   "title": "Objects collected during GC",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "python_gc_objects_collected_total{job=\"chaddi-tg\"}",
     "legendFormat": "{{generation}}"
    }
   ]
  },
  {
   "title": "Top Mom Victims",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chaddi_mom_victim_count_total{job=\"chaddi-tg\"}",
     "legendFormat": "{{user_id}}"
    }
   ]
  },
  {
   "title": "Top Mom Invokers",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 7, "x": 8, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chaddi_mom_invoker_count_total{job=\"chaddi-tg\"}",
     "legendFormat": "{{user_id}}"
    }
   ]
  },
  {
   "title": "Gamblers by Group",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 9, "x": 15, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chaddi_gamble_count_total{job=\"chaddi-tg\"}",
     "legendFormat": "{{user_id}}"
    }
   ]
  },
  {
   "title": "Top Mom2 Victims",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chaddi_mom2_victim_count_total{job=\"chaddi-tg\"}",
     "legendFormat": "{{user_id}}"
    }
   ]
  },
  {
   "title": "Top Mom2 Invokers",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 7, "x": 8, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chaddi_mom2_invoker_count_total{job=\"chaddi-tg\"}",
     "legendFormat": "{{user_id}}"
    }
   ]
  },
  {
   "title": "Roll Metrics",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 9, "x": 15, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chaddi_rolls_started_total{job=\"chaddi-tg\"}",
     "legendFormat": "Rolls Started"
    },
    {
     "expr": "chaddi_rolls_won_total{job=\"chaddi-tg\"}",
     "legendFormat": "Rolls Won"
    },
    {
     "expr": "chaddi_rolls_attempted_total{job=\"chaddi-tg\"}",
     "legendFormat": "Dice Rolls Handled"
    }
   ]
  }
 ]
}