name: API - Build + Deploy

on:
  push:
    branches: [ master, dev/api ]

defaults:
  run:
    working-directory: "monitoring/api"

jobs:

  build:
    name: Build Binary
    runs-on: ubuntu-latest

    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: debug
      run: ls && pwd

    - name: Build the API Binary
      run: go build -o chaddi-api main.go
